version: "3.3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
  corfumv:
    build:
      context: .
      dockerfile: docker/corfumv.Dockerfile
    container_name: corfumv
    environment:
      MONGO: mongodb://root:secret@mongodb:27017
      SYNC: True
    volumes:
      - "./corfumv:/app/corfumv"
    ports:
      - "11000:11000"
    entrypoint: uvicorn corfumv.server:app --host 0.0.0.0 --port 11000 --reload
  lab:
    build:
      context: .
      dockerfile: docker/lab.Dockerfile
    container_name: lab_corfumv
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/app/dist
      - ./lab:/app/lab
    entrypoint: jupyter lab --ip=0.0.0.0 --port=8080 --no-browser --allow-root